apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-templates
  namespace: monitoring
data:
  alert-templates.json: |
    {
      "resolved_template": [
        "**{alertname} âœ… å‘Šè­¦æ¢å¤** ğŸŒ¤ï¸ \n",
        "**å‘Šè­¦çº§åˆ«**: {severity} ({level}çº§)\n",
        "**å¼€å§‹æ—¶é—´ï¼ˆæœ¬åœ°ï¼‰**: {starts_at}\n",
        "**ç»“æŸæ—¶é—´ï¼ˆæœ¬åœ°ï¼‰**: {ends_at}\n",
        "**å‘Šè­¦å†…å®¹**: {description}\n"
      ],
      "firing_template": [
        "**{alertname} ğŸš¨ å‘Šè­¦é€šçŸ¥** âš ï¸ \n",
        "**å‘Šè­¦çº§åˆ«**: {severity} ({level}çº§)\n",
        "**å¼€å§‹æ—¶é—´ï¼ˆæœ¬åœ°ï¼‰**: {starts_at}\n",
        "**ç»“æŸæ—¶é—´ï¼ˆæœ¬åœ°ï¼‰**: {ends_at}\n",
        "**å‘Šè­¦å†…å®¹**: {description}\n"
      ]
    }